language: php
php:
  - 5.5

install:
  - composer self-update && composer --version
  - echo "yes" | pecl install apcu-beta
  - pushd src/protected; composer update --prefer-dist; popd

before_script:
  - psql -c 'create user mapasculturais;' -U postgres
  - psql -c 'create database mapasculturais owner mapasculturais;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d mapasculturais
  - psql -f db/schema.sql -U mapasculturais -d mapasculturais
  - psql -f db/test-data.sql -U mapasculturais -d mapasculturais

  - tar xC db -f db/sp-shapefile-sql.tar.xz
  - psql -c "DROP table IF EXISTS sp_regiao;" -U mapasculturais -d mapasculturais
  - psql -f db/sp-shapefile-sql/sp_regiao.sql -U mapasculturais -d mapasculturais
  - psql -c "DROP table IF EXISTS sp_distrito;" -U mapasculturais -d mapasculturais
  - psql -f db/sp-shapefile-sql/sp_distrito.sql -U mapasculturais -d mapasculturais
  - psql -c "DROP table IF EXISTS sp_subprefeitura;" -U mapasculturais -d mapasculturais
  - psql -f db/sp-shapefile-sql/sp_subprefeitura.sql -U mapasculturais -d mapasculturais

  - echo "apc.cli_enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -S localhost:8000 -t src > /dev/null &

script:
  - phpunit tests

notifications:
  hipchat:
    on_success: change
    rooms:
      secure: 6KVjKLIde59VWYmJbXx0okMUEhU9gjcl55X+AdW4q1zLo8/cHNhW9iz4De45CfE0gruBgw14h0hOU8QPxJx/4KwgVoSm9PoJopHmYy7SKmSBCwlcxm6Symw9IYVQo5B/hfZlr+gqtUPT8emiBVzvhnTk6DVjZhJbFg2oyp7s+uA=
