language: php
php:
    - 5.5

install:
    - cd src/protected; composer update

before_script:
    - psql -c 'create user mapasculturais;' -U postgres
    - psql -c 'create database mapasculturais owner mapasculturais;' -U postgres
    - psql -c 'CREATE EXTENSION postgis;' -U postgres -d mapasculturais
    # - psql -c 'CREATE EXTENSION postgis_topology;' -U mapasculturais -d mapasculturais
    - psql -f db/schema.sql -U mapasculturais -d mapasculturais
    - psql -f db/initial-data.sql -U mapasculturais -d mapasculturais
    - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - phpunit tests
