language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

install:
  - composer self-update && composer --version
  - if [[ $TRAVIS_PHP_VERSION =~ 5.4 ]] ; then echo 'extension="apc.so"' >> ./tests/travis/php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 7.0 ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu; fi;
  - pushd src/protected; composer install --prefer-dist; popd

before_script:
  - echo "apc.cli_enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - gem install sass
  - npm install -g uglify-js uglifycss autoprefixer

script:
  - ./scripts/run-tests.sh

notifications:
  slack:
    secure: 43vNQD7zOqTTbMnJnnSAOq1avTE0MkxcUAUNX7za6XHg6Q3Caa27K0hP0KQUjgZqqUWeg1jNo2mpq+mIsJCwpebfIA9ZPjmeKq5ryXNmdW7xbqVx7sq3KPKJxTYwJ0RBzuz3LTZALfhRJs8gD6ys+U5E5bOe/ZiGLyq/eQ9hfcw=
  hipchat:
    on_success: change
    rooms:
      secure: 6KVjKLIde59VWYmJbXx0okMUEhU9gjcl55X+AdW4q1zLo8/cHNhW9iz4De45CfE0gruBgw14h0hOU8QPxJx/4KwgVoSm9PoJopHmYy7SKmSBCwlcxm6Symw9IYVQo5B/hfZlr+gqtUPT8emiBVzvhnTk6DVjZhJbFg2oyp7s+uA=
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/68552e7377e32b765b22
    on_success: change
    on_failure: always
    on_start: false
