version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: docker/development/Dockerfile
    ports:
      - "80:80"
    volumes:
      # scripts principais
      - ../docker/entrypoint.sh:/entrypoint.sh
      - ../docker/jobs-cron.sh:/jobs-cron.sh
      - ../docker/recreate-pending-pcache-cron.sh:/recreate-pending-pcache-cron.sh

      - ../composer.json:/var/www/composer.json
      - ../composer.lock:/var/www/composer.lock

      - ../config:/var/www/config
      - ../public:/var/www/html
      - ../scripts:/var/www/scripts
      - ../src:/var/www/src
      - ../var:/var/www/var

      - ../docker/development/router.php:/var/www/html/router.php

      - ./config.d:/var/www/config/config.d

      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      

    links:
      - db
      - redis
    environment:
      - BUILD_ASSETS=1
      - PENDING_PCACHE_RECREATION_INTERVAL=15
      - JOBS_INTERVAL=15
      - REDIS_CACHE=redis
      - MAILER_TRANSPORT=smtp://mailhog:1025
      - MAILER_FROM=sysadmin@localhost
      
      # chaves de teste do google recaptcha
      - GOOGLE_RECAPTCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - GOOGLE_RECAPTCHA_SECRET=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    depends_on:
      - db
      - redis
      - mailhog
    stdin_open: true
    tty: true
    
  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
      

    ports:
      - "5470:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
