openapi: 3.0.2
info:
  title: API Mapas Culturais - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /
tags:
  - name: Oportunidades
    description: Everything about your tests
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /api/opportunity/find:
    $ref: './components/paths/opportunity/find.yaml'
  /api/opportunity/findOne:
    $ref: './components/paths/opportunity/find-one.yaml'
  /api/opportunity/describe:
    $ref: './components/paths/opportunity/describe.yaml'
  /api/opportunity/getTypes:
    $ref: './components/paths/opportunity/get-types.yaml'
  /api/opportunity/findRegistrations:
    $ref: './components/paths/opportunity/find-registrations.yaml'
  /api/opportunity/selectFields:
    $ref: './components/paths/opportunity/select-fields.yaml'

components:
  schemas:
    Opportunity:
      $ref: './components/schemas/opportunity.yaml'
    OpportunityType:
      $ref: './components/schemas/opportunity-type.yaml'