openapi: 3.0.2
info:
  title: API Mapas Culturais - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api
tags:
  - name: test1
    description: Everything about your tests
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: test2
    description: Access to Test orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: test3
    description: Operations about user
paths:
  /tests:
    get:
      tags:
        - tests
      summary: Retrieve all tests
      description: Retrieve all tests
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        properties:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 10
            petId:
              type: integer
              format: int64
              example: 198772
            quantity:
              type: integer
              format: int32
              example: 7
            shipDate:
              type: string
              format: date-time
            status:
              type: string
              description: Order Status
              example: approved
              enum:
                - placed
                - approved
                - delivered
            complete:
              type: boolean
          xml:
            name: order
      xml:
        name: order