openapi: 3.0.2
info:
  title: API Mapas Culturais - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /
tags:
  - name: Agentes
    description: Rotas relacionadas aos agentes
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Espaços
    description: Rotas relacionadas aos espaços
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Oportunidades
    description: Everything about your tests
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Projetos
    description: Rotas relacionadas aos projetos
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Selos
    description: Rotas relacionadas aos selos
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /api/agent/find:
    $ref: './components/paths/agent/find.yaml'
  /api/opportunity/find:
    $ref: './components/paths/opportunity/find.yaml'
  /api/opportunity/findOne:
    $ref: './components/paths/opportunity/find-one.yaml'
  /api/opportunity/describe:
    $ref: './components/paths/opportunity/describe.yaml'
  /api/opportunity/getTypes:
    $ref: './components/paths/opportunity/get-types.yaml'
  /api/opportunity/findRegistrations:
    $ref: './components/paths/opportunity/find-registrations.yaml'
  /api/opportunity/selectFields:
    $ref: './components/paths/opportunity/select-fields.yaml'
  /api/project/describe:
    $ref: './components/paths/project/describe.yaml'
  /api/project/find:
    $ref: './components/paths/project/find.yaml'
  /api/space/describe:
    $ref: './components/paths/space/describe.yaml'
  /api/space/find:
    $ref: './components/paths/space/find.yaml'
  /api/space/findOne:
    $ref: './components/paths/space/find-one.yaml'
  /api/space/findByEvents:
    $ref: './components/paths/space/find-by-events.yaml'
  /api/space/getTypes:
    $ref: './components/paths/space/get-types.yaml'
  /api/space/getTypeGroups:
    $ref: './components/paths/space/get-type-groups.yaml'
  /api/seal/describe:
    $ref: './components/paths/seal/describe.yaml'
  /api/seal/find:
    $ref: './components/paths/seal/find.yaml'
  /api/seal/findOne:
    $ref: './components/paths/seal/find-one.yaml'
  /api/seal/getTypes:
    $ref: './components/paths/seal/get-types.yaml'
  /api/seal/getTypeGroups:
    $ref: './components/paths/seal/get-type-groups.yaml'
components:
  schemas:
    Agent:
      $ref: './components/schemas/agent.yaml'
    Opportunity:
      $ref: './components/schemas/opportunity.yaml'
    OpportunityType:
      $ref: './components/schemas/opportunity-type.yaml'
    ProjectDescribe:
      $ref: './components/schemas/project-describe.yaml'
    Project:
      $ref: './components/schemas/project.yaml'
    Space:
      $ref: './components/schemas/space.yaml'
    SpaceType:
      $ref: './components/schemas/space-type.yaml'
    SpaceTypeGroup:
      $ref: './components/schemas/space-type-group.yaml'
    Seal:
      $ref: './components/schemas/seal.yaml'
    SealType:
      $ref: './components/schemas/seal-type.yaml'
    SealTypeGroup:
      $ref: './components/schemas/seal-type-groups.yaml'
    SealDescribe:
      $ref: './components/schemas/seal-describe.yaml'
